- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: projectcalico
    repo_url: https://docs.tigera.io/calico/charts

- name: Deploy calico {{ calico_version }}
  kubernetes.core.helm:
    name: calico
    release_namespace: calico
    create_namespace: true
    chart_ref: projectcalico/tigera-operator
    chart_version: "{{ calico_version }}"
    values: "{{ lookup('file', 'cni-values.yaml') | from_yaml }}"
    kubeconfig: /etc/kubernetes/admin.conf
    context: kubernetes-admin@leonov
